trigger:
 branches:
  include:
   - develop
   - master

jobs:
- job: RunsInContainer
  pool:
    vmImage: 'macos-10.14'
  # container: clusterbrix/public-vvjva8k8gdrc:cordova # Docker Hub image reference
  steps:
  # - script: |
  #     mkdir ~/.npm
  #     npm config set prefix '~/.npm'
  #     export PATH=~/.npm/bin:$PATH
  #     npm install -g "@quasar/cli"
  #     pwd
  #     quasar build -m cordova -T android
  # displayName: 'Install JDK'


  - task: NodeTool@0
    inputs:
      versionSpec: '8.15.0'
    displayName: 'Install Node.js'

  - script: |
      npm cache clean -f && npm install -g --unsafe-perm node-sass @quasar/cli && npm install
    displayName: 'npm install'

  - script: |
     npm run security:audit
    displayName: 'Run npm dependancy security audit'

  #Tmporary commented out to test installation
  - script: |
      npm run test:unit
    displayName: 'Run unit test'
