trigger:
 branches:
  include:
   - develop
   - master

jobs:
- job: RunsInContainer
  container: ubuntu:16.04 # Docker Hub image reference
  steps:
  - script: |
      apt-get update
      apt-get install -y curl sudo
  displayName: 'Install JDK'


# - task: NodeTool@0
#   inputs:
#     versionSpec: '8.15.0'
#   displayName: 'Install Node.js'
#
# - script: |
#     npm cache clean -f && npm install -g --unsafe-perm node-sass && npm install
#   displayName: 'npm install'

#- script: |
#    npm run security:audit
#  displayName: 'Run npm dependancy security audit'

#Temporary commented out to test installation
# - script: |
#     npm run test:unit
#   displayName: 'Run unit test'
