trigger:
  branches:
    include:
      - develop
      - master

jobs:
  - job: RunsInContainer
    pool:
      vmImage: 'macos-10.14'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.15.0'
        displayName: 'Install Node.js'

      - script: |
          npm cache clean -f && npm install -g --unsafe-perm node-sass cordova @quasar/cli@^1.0.0-beta.4 && npm install
        displayName: 'npm install'

      #Tmporary commented out to test installation
      - script: |
          npm run test:unit
        displayName: 'Run unit test'

      - script: |
          quasar build -m cordova -T android
        displayName: 'build android'
