trigger:
- develop
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.15.0'
  displayName: 'Install Node.js'

- script: |
    npm cache clean -f && npm install -g --unsafe-perm node-sass && npm install
  displayName: 'npm install'

#- script: |
#    npm run security:audit
#  displayName: 'Run npm dependancy security audit'

#Temporary commented out to test installation
# - script: |
#     npm run test:unit
#   displayName: 'Run unit test'


- script: |
    sudo apt-get install openjdk-8-jre and sudo apt-get install openjdk-8-jdk
  displayName: 'Install prerequisites'
