image: node:8.15.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm audit
          - node node_modules/snyk/cli auth ${SNYK_TOKEN} -d
          - node node_modules/snyk/cli protect
          - npm test
          - if [ $BITBUCKET_BRANCH == "master" ]; then node node_modules/snyk/cli monitor; fi; 
