trigger:
- develop
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.15.0'
  displayName: 'Install Node.js'

- script: |
    npm cache clean -f && npm install -g --unsafe-perm cordova @quasar/cli node-sass && npm install
  displayName: 'npm install'

- script: |
    quasar build -m cordova -T ios
  displayName: 'Compile Cordova Android'
